<?php

/**
 * Shared in-memory ObjectService double for unit tests.
 *
 * WHY THIS EXISTS (ADR-084)
 * ------------------------
 * Before ADR-084 these tests handed a duck-typed anonymous class to a
 * ContainerInterface mock and let production resolve it by string id. Nothing
 * checked that the anonymous class matched OpenRegister's service: one of the
 * doubles it replaced declared
 *
 *     saveObject(string $register = '', string $schema = '', array $object = [], ?string $uuid = null)
 *
 * while production has always declared `saveObject(array $object, ...)` first.
 * The duck type could never have satisfied the real service, and no test could
 * see that, because the container mock was never consulted by anything.
 *
 * The double below is generated by PHPUnit from
 * OCA\OpenRegister\Contract\ObjectServiceInterface itself, so:
 *   - a method the contract does not declare cannot be configured
 *     (MethodCannotBeConfiguredException at configure time);
 *   - a callback whose return type does not match the contract's fails at call
 *     time rather than quietly handing production a shape it cannot receive;
 *   - `instanceof ObjectServiceInterface` is true, which is what every
 *     constructor now requires.
 *
 * Verified against openregister@development, lib/Contract/ObjectServiceInterface.php:
 *   saveObject()  line 152
 *   setRegister() line 174
 *   find()        line 191
 *   findAll()     line 212
 *   setSchema()   line 225
 *
 * Only those five are modelled. Anything else stays an unconfigured mock method,
 * which is the honest answer for a call this fixture does not describe.
 *
 * @category Test
 * @package  OCA\Decidesk\Tests\Unit\Support
 *
 * @author    Conduction Development Team <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @link https://conduction.nl
 */

declare(strict_types=1);

namespace OCA\Decidesk\Tests\Unit\Support;

use OCA\OpenRegister\Contract\ObjectEntityInterface;
use OCA\OpenRegister\Contract\ObjectServiceInterface;
use OCA\OpenRegister\Db\ObjectEntity;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * Builds an ObjectServiceInterface mock backed by an in-memory row store.
 */
trait InMemoryObjectService {

	/**
	 * Build an ObjectServiceInterface double over an in-memory row store.
	 *
	 * Rows are `['schema' => <slug>, 'object' => <payload>]` keyed by object id.
	 * The store and the save recorder are passed by reference so a test can seed
	 * them beforehand and assert on them afterwards.
	 *
	 * @param \ArrayObject<string, array{schema: string, object: array<string, mixed>}> $store  The row store.
	 * @param \ArrayObject<int, array{schema: string, object: array<string, mixed>}>    $saves  Recorder for saveObject() payloads.
	 * @param bool                                                                     $scopeFindBySchema Whether find() honours an explicit schema argument.
	 *
	 * @return ObjectServiceInterface&MockObject
	 */
	private function makeInMemoryObjectService(
		\ArrayObject $store,
		\ArrayObject $saves,
		bool $scopeFindBySchema = true,
	): ObjectServiceInterface {
		/*
		 * @var TestCase $this
		 */
		$objectService = $this->createMock(ObjectServiceInterface::class);
		$selectedSchema = '';

		$objectService->method('setRegister')->willReturnSelf();
		$objectService->method('setSchema')->willReturnCallback(
			function (string|int $schema) use (&$selectedSchema, &$objectService): ObjectServiceInterface {
				$selectedSchema = (string) $schema;
				return $objectService;
			}
		);

		$objectService->method('find')->willReturnCallback(
			function (
				int|string $id,
				?array $_extend = [],
				bool $files = false,
				string|int|null $register = null,
				string|int|null $schema = null,
			) use ($store, $scopeFindBySchema): ?ObjectEntityInterface {
				$row = ($store[(string) $id] ?? null);
				if ($row === null) {
					return null;
				}

				if ($scopeFindBySchema === true && $schema !== null && $row['schema'] !== (string) $schema) {
					return null;
				}

				return $this->makeObjectEntityDouble($row['object']);
			}
		);

		$objectService->method('findAll')->willReturnCallback(
			function (array $config = []) use ($store, &$selectedSchema): array {
				$out = [];
				foreach ($store as $row) {
					if ($selectedSchema !== '' && $row['schema'] !== $selectedSchema) {
						continue;
					}

					$matches = true;
					foreach (($config['filters'] ?? []) as $key => $value) {
						// Relation filters are resolved by the engine, not by a
						// plain field comparison; they are out of scope here.
						if (str_starts_with((string) $key, '_relations.') === true) {
							continue;
						}

						if (($row['object'][$key] ?? null) !== $value) {
							$matches = false;
							break;
						}
					}

					if ($matches === true) {
						$out[] = $this->makeObjectEntityDouble($row['object']);
					}
				}

				return $out;
			}
		);

		$objectService->method('saveObject')->willReturnCallback(
			function (
				array $object,
				?array $extend = [],
				string|int|null $register = null,
				string|int|null $schema = null,
				?string $uuid = null,
			) use ($store, $saves, &$selectedSchema): ObjectEntityInterface {
				$slug = ($schema !== null) ? (string) $schema : $selectedSchema;
				$saves->append(['schema' => $slug, 'object' => $object]);
				$id = (string) ($uuid ?? $object['id'] ?? $object['uuid'] ?? ('new-' . count($saves)));
				$store[$id] = ['schema' => $slug, 'object' => $object];
				return $this->makeObjectEntityDouble($object);
			}
		);

		return $objectService;
	}//end makeInMemoryObjectService()

	/**
	 * Wrap a payload in an ObjectEntityInterface double.
	 *
	 * The bundled stub OCA\OpenRegister\Db\ObjectEntity implements
	 * ObjectEntityInterface, so this satisfies the return type production
	 * declares on find() / findAll() / saveObject().
	 *
	 * @param array<string, mixed> $object The payload.
	 *
	 * @return ObjectEntityInterface
	 */
	private function makeObjectEntityDouble(array $object): ObjectEntityInterface {
		/*
		 * @var TestCase $this
		 */
		$entity = $this->createMock(ObjectEntity::class);
		$entity->method('jsonSerialize')->willReturn($object);
		$entity->method('getObject')->willReturn($object);
		$entity->method('getUuid')->willReturn((string) ($object['uuid'] ?? $object['id'] ?? ''));
		return $entity;
	}//end makeObjectEntityDouble()
}//end trait
